-- Migration v2 — financial columns for vendas dashboard

ALTER TABLE stores
  ADD COLUMN IF NOT EXISTS imposto_pct NUMERIC DEFAULT 0;

ALTER TABLE items
  ADD COLUMN IF NOT EXISTS cost NUMERIC DEFAULT 0;

ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS item_id TEXT,
  ADD COLUMN IF NOT EXISTS quantity INT DEFAULT 1,
  ADD COLUMN IF NOT EXISTS unit_price NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ml_fee NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS shipping_type TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS shipping_cost NUMERIC DEFAULT 0;
